-- SUBCONSULTAS PARTE 2

SELECT MAX(peso) FROM CLINICA.EXPEDIENTE_DIAGNOSTICO;

-- LAMINA 57

SELECT * FROM CLINICA.EXPEDIENTE_DIAGNOSTICO
WHERE peso IN (SELECT MAX(peso)
			FROM CLINICA.EXPEDIENTE_DIAGNOSTICO);
			
-- LAMINA 59

SELECT * FROM CLINICA.EXPEDIENTE_DIAGNOSTICO
WHERE peso IN (SELECT MAX(peso)
			FROM CLINICA.EXPEDIENTE_DIAGNOSTICO)
OR edad IN (SELECT MAX(edad)
		FROM CLINICA.EXPEDIENTE_DIAGNOSTICO)

-- LAMINA 60

SELECT * FROM CLINICA.EXPEDIENTE_DIAGNOSTICO
WHERE peso IN (SELECT MIN(peso)
			FROM CLINICA.EXPEDIENTE_DIAGNOSTICO)
OR edad IN (SELECT MIN(edad)
			FROM CLINICA.EXPEDIENTE_DIAGNOSTICO)
			
-- LAMINA 62

SELECT * FROM CLINICA.PACIENTE WHERE pk_idPaciente = 'P-0001'

-- LAMINA 63

SELECT *, (SELECT tipoSangre FROM CLINICA.EXPEDIENTE WHERE pk_idPaciente = PACIENTE.pk_idPaciente)
FROM CLINICA.PACIENTE WHERE pk_idPaciente = 'P-0001'

-- LAMINA 64

SELECT *, (SELECT tipoSangre FROM CLINICA.EXPEDIENTE WHERE pk_idPaciente = PACIENTE.pk_idPaciente),
(SELECT padecimientocro FROM CLINICA.EXPEDIENTE WHERE pk_idPaciente = PACIENTE.pk_idPaciente)
FROM CLINICA.PACIENTE WHERE pk_idPaciente = 'P-0001'
						