--SUBCONSULTAS PARTE 1

SELECT * FROM CLINICA.ESPECIALISTA
WHERE pk_idEspecialista IN (SELECT fk_idEspecialista
							FROM CLINICA.AGENDAR_CITA
							WHERE fechaCita BETWEEN '2022-10-04' AND '2022-10-08');
							
-- LAMINA 51

SELECT * FROM CLINICA.ESPECIALISTA
WHERE pk_idEspecialista IN (SELECT fk_idEspecialista
							FROM CLINICA.AGENDAR_CITA
							WHERE fechaCita BETWEEN '2022-10-04' AND '2022-10-05');
							
-- LAMINA 52

SELECT * FROM CLINICA.ESPECIALISTA
WHERE pk_idEspecialista NOT IN (SELECT fk_idEspecialista
								FROM CLINICA.AGENDAR_CITA
								WHERE fechaCita BETWEEN '2022-10-04' AND '2022-10-05');
								
-- LAMINA 53

SELECT * FROM CLINICA.PACIENTE
INNER JOIN CLINICA.EXPEDIENTE_DIAGNOSTICO
ON PACIENTE.pk_idPaciente = EXPEDIENTE_DIAGNOSTICO.fk_idPaciente
WHERE ( sexo = 'M' )
AND EXPEDIENTE_DIAGNOSTICO.fk_idEspecialista IN (SELECT pk_idEspecialista
						FROM CLINICA.ESPECIALISTA
						WHERE  pk_idEspecialista IN ('ME-0001' , 'ME-0003'))
						