JOINS
	--1. INNER JOIN
	SELECT * FROM CLINICA.PACIENTE
	INNER JOIN CLINICA.EXPEDIENTE
	ON PACIENTE.pk_idPaciente = EXPEDIENTE.pk_idPaciente
	WHERE PACIENTE.pk_idPaciente = 'P-0001';
	
	--2. LEFT Y RIGHT JOIN
	INSERT INTO CLINICA.PACIENTE VALUES ('P-0011', 'DANIELA', 'VELEZ', 'F', '1990-01-01', 'MANABI', 'JARAMIJO', '0999999999');
	
	SELECT * FROM CLINICA.PACIENTE
	LEFT JOIN CLINICA.EXPEDIENTE
	ON PACIENTE.pk_idPaciente = EXPEDIENTE.pk_idPaciente;
	
	SELECT * FROM CLINICA.PACIENTE
	RIGHT JOIN CLINICA.EXPEDIENTE
	ON PACIENTE.pk_idPaciente = EXPEDIENTE.pk_idPaciente
	
	--3. INNER JOIN ANIDADO
	SELECT * FROM CLINICA.PACIENTE
	INNER JOIN CLINICA.CITA
	ON PACIENTE.pk_idPaciente = CITA.fk_idPaciente
	INNER JOIN CLINICA.AGENDAR_CITA
	ON CITA.pk_idcita = AGENDAR_CITA.fk_idcita
	INNER JOIN CLINICA.ESPECIALISTA
	ON AGENDAR_CITA.fk_idEspecialista = ESPECIALISTA.pk_idEspecialista
	INNER JOIN CLINICA.EXPEDIENTE_DIAGNOSTICO
	ON ESPECIALISTA.pk_idEspecialista = EXPEDIENTE_DIAGNOSTICO.fk_idEspecialista
	INNER JOIN CLINICA.EXPEDIENTE
	ON EXPEDIENTE_DIAGNOSTICO.fk_idPaciente = EXPEDIENTE.pk_idPaciente
	WHERE PACIENTE.pk_idPaciente = 'P-0002';
