-- CREAR UNA VISTA
CREATE VIEW CLINICA.PACIENTE_MASCULINOS AS
SELECT * FROM CLINICA.PACIENTE WHERE sexo = 'M';

--EJECUTAR UNA VISTA
SELECT * FROM CLINICA.PACIENTE_MASCULINOS;


--ELIMINAR UNA VISTA
DROP VIEW CLINICA.PACIENTE_MASCULINOS;