REVOKE SELECT, INSERT, UPDATE 
ON CLINICA.PACIENTE, CLINICA.CITA, CLINICA.AGENDAR_CITA
FROM recepcionista;

REVOKE DELETE ON CLINICA.PACIENTE FROM recepcionista;

REVOKE USAGE ON SCHEMA CLINICA FROM recepcionista;

