--DBA 
--CREAR ROLE DBA
CREATE ROLE dba WITH SUPERUSER;

GRANT USAGE ON SCHEMA CLINICA TO dba;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA CLINICA TO dba WITH GRANT OPTION; 

CREATE USER administrador WITH PASSWORD '12345' IN ROLE dba;