--FOR LOOP

CREATE OR REPLACE FUNCTION CLINICA.Loop(numero INT) 
RETURNS INT AS $$
DECLARE
	i INT :=0;
BEGIN 
     FOR i IN 1..numero LOOP
	 RAISE NOTICE 'CONTADOR %', i;
		END LOOP;
END;
$$ LANGUAGE plpgsql;

SELECT CLINICA.Loop(5);
