--FOR LOOP

CREATE OR REPLACE FUNCTION CLINICA.LoopCada2(numero INT) 
RETURNS INT AS $$
DECLARE
	i INT :=0;
BEGIN 
     FOR i IN  0..numero BY 2 LOOP
	 RAISE NOTICE 'CONTADOR %', i;
		END LOOP;
END;
$$ LANGUAGE plpgsql;

SELECT CLINICA.LoopCada2(20);