--FOR LOOP

CREATE OR REPLACE FUNCTION CLINICA.LoopInversa(numero INT) 
RETURNS INT AS $$
DECLARE
	i INT :=0;
BEGIN 
     FOR i IN REVERSE numero..1 LOOP
	 RAISE NOTICE 'CONTADOR %', i;
		END LOOP;
END;
$$ LANGUAGE plpgsql;

SELECT CLINICA.LoopInversa(10);