CREATE DATABASE "Clinica_Postgres"
    WITH 
    OWNER = postgres
    ENCODING = 'UTF8';
	
CREATE SCHEMA CLINICA AUTHORIZATION postgres;

DROP SCHEMA PUBLIC;

CREATE DOMAIN CLINICA.ID_PACIENTE AS CHAR(6) NOT NULL
	CHECK (VALUE ~ '^[P]{1}[-]{1}\d{4}$'); 

CREATE DOMAIN CLINICA.ID_MEESPECIALISTA AS CHAR(7) NOT NULL
	CHECK (VALUE ~ '^[ME]{2}[-]{1}\d{4}$');
	
CREATE DOMAIN CLINICA.ID_CITA AS CHAR(7) NOT NULL
	CHECK (VALUE ~ '^[CM]{2}[-]{1}\d{4}$'); 
	
	
CREATE TABLE CLINICA.PACIENTE (
	pk_idPaciente CLINICA.ID_PACIENTE,
	nombre VARCHAR(20) NOT NULL,
	apellido VARCHAR(20) NOT NULL,
	sexo CHAR(1) NOT NULL,
	fechaNacimiento DATE NOT NULL,
	ciudad VARCHAR(20) NOT NULL,
	estado VARCHAR(20) NOT NULL,
	telefono CHAR(10) UNIQUE,
	PRIMARY KEY (pk_idPaciente)
);

CREATE TABLE CLINICA.ESPECIALISTA(
	pk_idEspecialista CLINICA.ID_MEESPECIALISTA,
	nombre VARCHAR(20) NOT NULL,
	apellido VARCHAR(20) NOT NULL,
	sexo CHAR(1) NOT NULL,
	fechaNacimiento DATE NOT NULL,
	especialidad VARCHAR(30) NOT NULL,
	PRIMARY KEY (pk_idEspecialista)
	
	CREATE DATABASE "Clinica_Postgres"
    WITH 
    OWNER = postgres
    ENCODING = 'UTF8';
	
CREATE SCHEMA CLINICA AUTHORIZATION postgres;

DROP SCHEMA PUBLIC;

CREATE DOMAIN CLINICA.ID_PACIENTE AS CHAR(6) NOT NULL
	CHECK (VALUE ~ '^[P]{1}[-]{1}\d{4}$'); 

CREATE DOMAIN CLINICA.ID_MEESPECIALISTA AS CHAR(7) NOT NULL
	CHECK (VALUE ~ '^[ME]{2}[-]{1}\d{4}$');
	
CREATE DOMAIN CLINICA.ID_CITA AS CHAR(7) NOT NULL
	CHECK (VALUE ~ '^[CM]{2}[-]{1}\d{4}$'); 
	
	
CREATE TABLE CLINICA.PACIENTE (
	pk_idPaciente CLINICA.ID_PACIENTE,
	nombre VARCHAR(20) NOT NULL,
	apellido VARCHAR(20) NOT NULL,
	sexo CHAR(1) NOT NULL,
	fechaNacimiento DATE NOT NULL,
	ciudad VARCHAR(20) NOT NULL,
	estado VARCHAR(20) NOT NULL,
	telefono CHAR(10) UNIQUE,
	PRIMARY KEY (pk_idPaciente)
);

CREATE TABLE CLINICA.ESPECIALISTA(
	pk_idEspecialista CLINICA.ID_MEESPECIALISTA,
	nombre VARCHAR(20) NOT NULL,
	apellido VARCHAR(20) NOT NULL,
	sexo CHAR(1) NOT NULL,
	fechaNacimiento DATE NOT NULL,
	especialidad VARCHAR(30) NOT NULL,
	PRIMARY KEY (pk_idEspecialista)
);

CREATE TABLE CLINICA.EXPEDIENTE (
	pk_idPaciente CLINICA.ID_PACIENTE,
	tipoSangre VARCHAR(10) NOT NULL,
	tipoAlergia VARCHAR(50) NOT NULL,
	padecimientoCro VARCHAR(50) NOT NULL,
	fechaCreacion TIMESTAMP NOT NULL,
	PRIMARY KEY (pk_idPaciente),
	FOREIGN KEY (pk_idPaciente) REFERENCES CLINICA.PACIENTE(pk_idPaciente)
	ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE CLINICA.EXPEDIENTE_DIAGNOSTICO(
	folio SERIAL NOT NULL,
	fk_idEspecialista CLINICA.ID_MEESPECIALISTA,
	fk_idPaciente CLINICA.ID_PACIENTE,
	edad CHAR(3) NOT NULL,
	peso CHAR(3) NOT NULL,
	altura CHAR(4) NOT NULL,
	IMC CHAR(5) NOT NULL,
	nivelPeso CHAR(10) NOT NULL,
	presionArterial CHAR(8) NOT NULL,
	diagnostico VARCHAR(150) NOT NULL,
	recetario VARCHAR(150) NOT NULL,
	fechaCreacion TIMESTAMP NOT NULL,
	PRIMARY KEY (folio),
	FOREIGN KEY (fk_idEspecialista) REFERENCES CLINICA.ESPECIALISTA(pk_idEspecialista)
	ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (fk_idPaciente) REFERENCES CLINICA.EXPEDIENTE(pk_idPaciente)
	ON UPDATE CASCADE ON DELETE CASCADE
);


);

);