
--4.- SELECCIONAR LAS LLAVES FORANEAS DE PACIENTE Y ESPECIALISTA UTILIZANDO LA INSTRUCCION 
-- DISTINCT DE LA TABLA DE EXPEDIENTE DIAGNOSTICO

SELECT DISTINCT (fk_idPaciente, fk_idEspecialista)  
FROM CLINICA.EXPEDIENTE_DIAGNOSTICO;

--5.- SELECCIONAR LAS COLUMNAS DE FOLIO, ID DE PACIENTE, ID DE ESPECIALISTA Y FECHA DE CREACION 
--LOS DIAGNOSTICOS DE LOS PACIENTE QUE TENGAN UNA EDAD MAYOR A 25 Y SU NIVEL DE PESO NO SEA NORMAL,
--ADEMÁS QUE SU FECHA DE DIAGNOSTICO SEA MAYOR A OCTUBRE DEL 2022, ORDENARLOS POR EL ID DE ESPECIALISTA. 

SELECT folio, fk_idPaciente, fk_idEspecialista, fechaCreacion, nivelPeso FROM CLINICA.EXPEDIENTE_DIAGNOSTICO
WHERE nivelPeso NOT IN ('NORMAL') AND edad > '25' AND fechaCreacion > '2022-10-01'
ORDER BY fk_idEspecialista;

--6.- SELECCIONAR LOS ESPECIALISTAS QUE HAYAN HECHO DIAGNOSTICOS CUYO NIVEL DE PESO SEA SOBREPESO.

SELECT * FROM CLINICA.ESPECIALISTA
WHERE pk_idEspecialista IN (SELECT fk_idEspecialista
							FROM CLINICA.EXPEDIENTE_DIAGNOSTICO
							WHERE nivelPeso IN ('SOBREPESO'));
							

