
--11.- SELECCIONAR LOS DIAGNOSTICOS, ADEMÁS EXTRAER LOS PACIENTES QUE SEAN DE SEXO MASCULINO,
--POR ÚLTIMO EXTRAER LAS COLUMNAS DE NOMBRE, APELLIDO Y ESPECIALIDAD DE LA TABLA DE ESPECIALISTA

SELECT *,(SELECT nombre FROM CLINICA.ESPECIAlISTA WHERE pk_idEspecialista = EXPEDIENTE_DIAGNOSTICO.fk_idEspecialista),
(SELECT apellido FROM CLINICA.ESPECIAlISTA WHERE pk_idEspecialista = EXPEDIENTE_DIAGNOSTICO.fk_idEspecialista),
(SELECT especialidad FROM CLINICA.ESPECIAlISTA WHERE pk_idEspecialista = EXPEDIENTE_DIAGNOSTICO.fk_idEspecialista)
FROM CLINICA.EXPEDIENTE_DIAGNOSTICO 
WHERE fk_idPaciente IN (SELECT pk_idPaciente FROM CLINICA.PACIENTE
					   WHERE sexo = 'M')

--12.-MEDIANTE UN INNER JOIN SELECCIONAR LAS TABLAS DE PACIENTE CITA Y AGENDAR CITA, EN DONDE LA FECHA DE CITA 
-- ESTE ENTRE DOS FECHAS ADEMÁS QUE LAS CIUDADES DE LOS PACIENTES SEAN MANTA O PORTOVIEJO, 
-- POR ULTIMO QUE EL TIPO DE SANGRE DE LOS PACIENTES SEA O POSITIVO

SELECT * FROM CLINICA.PACIENTE
INNER JOIN CLINICA.CITA
ON PACIENTE.pk_idPaciente = CITA.fk_idPaciente
INNER JOIN CLINICA.AGENDAR_CITA
ON CITA.pk_idCita = AGENDAR_CITA.fk_idCita
WHERE AGENDAR_CITA.fechaCita BETWEEN '2022-10-04' AND '2022-10-08'
AND PACIENTE.ciudad IN('MANTA', 'PORTOVIEJO')
AND PACIENTE.pk_idPaciente IN (SELECT pk_idPaciente FROM CLINICA.EXPEDIENTE
							  WHERE tipoSangre ='O POSITIVO')
							  

